//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1434
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterAwayZwei {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class TwitterAwayZweiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TwitterAwayZweiStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwitterAwayZwei.TwitterAwayZweiStrings", typeof(TwitterAwayZweiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Check timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckTimelineUpdateNow {
            get {
                return ResourceManager.GetString("CheckTimelineUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection timuout. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionTimuout {
            get {
                return ResourceManager.GetString("ConnectionTimuout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hour(s) ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HourAgo {
            get {
                return ResourceManager.GetString("HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} min(s) ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinAgo {
            get {
                return ResourceManager.GetString("MinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not able to be fetch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotAbleToBeFetch {
            get {
                return ResourceManager.GetString("NotAbleToBeFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not able to be fetch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotAbleToBeUpdate {
            get {
                return ResourceManager.GetString("NotAbleToBeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [DMsg] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefixDirectMessage {
            get {
                return ResourceManager.GetString("PrefixDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Timeline] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefixTimeline {
            get {
                return ResourceManager.GetString("PrefixTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Twit] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefixTwitter {
            get {
                return ResourceManager.GetString("PrefixTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} sec(s) ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SecAgo {
            get {
                return ResourceManager.GetString("SecAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The user name or the password might be wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserNameORPasswordWrong {
            get {
                return ResourceManager.GetString("UserNameORPasswordWrong", resourceCulture);
            }
        }
    }
}
